<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * §08-10 — the money a bank takes without asking.
 *
 * Account maintenance, SMS alerts, commission on withdrawals, a charge for a
 * cheque book: a Bangladeshi current account quietly loses money every quarter
 * and none of it arrives as a bill. The two ways this goes wrong in practice are
 * also the two things this schema is shaped around:
 *
 *  · **Nobody records it, so the book stops matching the statement.** Hence a
 *    *rule*: the desk is told once that this account loses ৳500 every quarter,
 *    and from then on the charge posts on its own day, through the same journal
 *    service every other posting uses. What is charged is therefore never a
 *    number somebody retyped.
 *  · **Somebody records it twice.** A charge that came off the statement *and*
 *    was generated by a rule is the classic double-count, so the same rule
 *    cannot post twice for the same day — `bank_charges_rule_date_unique` is the
 *    referee — and the generator adopts what it finds instead of posting again.
 *    A hand-entered charge carries no rule id, so the index does not constrain
 *    it: a person recording what the bank did is a fact, not a duplicate.
 *
 * `basis` is on the rule rather than assumed: a fixed charge (maintenance) and a
 * commission on turnover are computed from different things — the second is read
 * off the account's own ledger, so the figure can be checked against the
 * statement instead of trusted.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('bank_charge_rules', function (Blueprint $table) {
            $table->id();
            $table->foreignId('company_id')->constrained()->restrictOnDelete();
            $table->foreignId('branch_id')->nullable()->constrained('branches')->nullOnDelete();

            // The account the bank takes the money from, and the expense account
            // it is booked to. Both are policy, so both are named.
            $table->foreignId('account_id')->constrained('accounts')->restrictOnDelete();
            $table->foreignId('expense_account_id')->constrained('accounts')->restrictOnDelete();

            $table->string('name', 120);
            $table->string('narration', 300)->nullable();

            // fixed = the bank charges this amount; percent = commission on the
            // money that left the account since the last charge (with a floor,
            // because “0.15% (min ৳100)” is how banks here write it).
            $table->string('basis', 12);
            $table->decimal('amount', 18, 4)->default(0);
            $table->decimal('rate_percent', 9, 6)->default(0);
            $table->decimal('min_amount', 18, 4)->default(0);

            $table->string('frequency', 16);
            $table->unsignedTinyInteger('day_of_month')->nullable();
            $table->date('starts_on');
            $table->date('ends_on')->nullable();

            $table->date('next_due_on')->nullable();
            $table->date('last_charged_on')->nullable();
            $table->unsignedInteger('charged_count')->default(0);
            $table->boolean('is_active')->default(true);

            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();

            $table->index(['company_id', 'is_active', 'next_due_on']);
            $table->index(['company_id', 'account_id']);
        });

        Schema::create('bank_charges', function (Blueprint $table) {
            $table->id();
            $table->foreignId('company_id')->constrained()->restrictOnDelete();
            $table->foreignId('branch_id')->nullable()->constrained('branches')->nullOnDelete();

            // Null when a person recorded what the bank did rather than a rule
            // generating it — a distinction the register shows.
            $table->foreignId('rule_id')->nullable()->constrained('bank_charge_rules')->nullOnDelete();

            $table->foreignId('account_id')->constrained('accounts')->restrictOnDelete();
            $table->foreignId('expense_account_id')->constrained('accounts')->restrictOnDelete();

            $table->string('charge_no', 40);
            $table->date('charged_on');
            $table->decimal('amount', 18, 4);

            // What the amount was computed from, kept on the row: a fixed figure
            // and a percentage of 4,20,000 of withdrawals look identical once they
            // are money, and only one of them can be checked against a statement.
            $table->string('basis', 12);
            $table->decimal('turnover', 18, 4)->default(0);
            $table->decimal('rate_percent', 9, 6)->default(0);

            $table->string('narration', 300)->nullable();
            $table->string('reference', 120)->nullable();

            // posted → reversed. A charge the bank reversed, or one keyed twice,
            // is answered with a reversal rather than an edit: the original really
            // did happen.
            $table->string('status', 16);
            $table->foreignId('journal_entry_id')->nullable()->constrained('journal_entries')->nullOnDelete();
            $table->foreignId('reversal_entry_id')->nullable()->constrained('journal_entries')->nullOnDelete();
            $table->foreignId('reversed_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('reversed_at')->nullable();
            $table->string('reversal_reason', 300)->nullable();

            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();

            $table->unique(['company_id', 'charge_no']);
            $table->unique(['rule_id', 'charged_on'], 'bank_charges_rule_date_unique');
            $table->index(['company_id', 'status', 'charged_on']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('bank_charges');
        Schema::dropIfExists('bank_charge_rules');
    }
};
