<?php

namespace App\Domain\CashBank;

use App\Domain\Accounting\Account;
use App\Domain\Accounting\JournalEntry;
use App\Domain\Foundation\Branch;
use App\Domain\Foundation\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * §08-10 — one charge a bank took, recorded as a real document.
 *
 * The only two lines it has in the ledger are the two that are true: the expense
 * the bank charged and the account it came out of (Dr the charge, Cr the bank).
 * Nothing here is a transfer, nothing is a payment to a party, and no other
 * account is invented — which is exactly why a bank charge deserves its own
 * document rather than being typed into the payment desk as if somebody had been
 * paid.
 *
 * `basis`, `turnover` and `rate_percent` travel with the money so the figure can
 * be checked: "0.15% of 4,20,000 of withdrawals" is an arithmetic a person can
 * verify against the statement, and a bare ৳630 is not.
 */
class BankCharge extends Model
{
    public const STATUS_POSTED = 'posted';

    public const STATUS_REVERSED = 'reversed';

    public const STATUSES = [
        self::STATUS_POSTED => 'Posted',
        self::STATUS_REVERSED => 'Reversed',
    ];

    protected $fillable = [
        'company_id', 'branch_id', 'rule_id', 'account_id', 'expense_account_id',
        'charge_no', 'charged_on', 'amount', 'basis', 'turnover', 'rate_percent',
        'narration', 'reference', 'status', 'journal_entry_id', 'reversal_entry_id',
        'reversed_by', 'reversed_at', 'reversal_reason', 'created_by',
    ];

    protected function casts(): array
    {
        return [
            'charged_on' => 'date',
            'amount' => 'decimal:4',
            'turnover' => 'decimal:4',
            'rate_percent' => 'decimal:6',
            'reversed_at' => 'datetime',
        ];
    }

    public function rule(): BelongsTo
    {
        return $this->belongsTo(BankChargeRule::class, 'rule_id');
    }

    public function account(): BelongsTo
    {
        return $this->belongsTo(Account::class, 'account_id');
    }

    public function expenseAccount(): BelongsTo
    {
        return $this->belongsTo(Account::class, 'expense_account_id');
    }

    public function journalEntry(): BelongsTo
    {
        return $this->belongsTo(JournalEntry::class, 'journal_entry_id');
    }

    public function reversalEntry(): BelongsTo
    {
        return $this->belongsTo(JournalEntry::class, 'reversal_entry_id');
    }

    public function reverser(): BelongsTo
    {
        return $this->belongsTo(User::class, 'reversed_by');
    }

    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function branch(): BelongsTo
    {
        return $this->belongsTo(Branch::class);
    }

    public function isReversed(): bool
    {
        return $this->status === self::STATUS_REVERSED;
    }

    public function statusLabel(): string
    {
        return self::STATUSES[$this->status] ?? (string) $this->status;
    }

    /** A charge a rule generated, or one a person recorded from the statement. */
    public function originLabel(): string
    {
        return $this->rule_id === null ? 'recorded by hand' : 'generated by '.($this->rule?->name ?? 'a rule');
    }

    /** "0.15% of 4,20,000.00 of withdrawals" — how the figure was arrived at. */
    public function basisLabel(): string
    {
        if ($this->basis !== BankChargeRule::BASIS_PERCENT) {
            return 'fixed charge';
        }

        $rate = rtrim(rtrim(number_format((float) $this->rate_percent, 4, '.', ''), '0'), '.');

        return $rate.'% of '.number_format((float) $this->turnover, 2).' of withdrawals';
    }

    /** The bank as a person would name it: the account's own name. */
    public function accountLabel(): string
    {
        return trim(($this->account?->code ?? '').' — '.($this->account?->name ?? ''), ' —');
    }
}
